### ISSUE TITLE
Adding tags throws an attribute error

### ISSUE THREAD

**Issue by BristleBeard** [kannibalox/pyrosimple#12]
This behavior is happening when trying to add a tag. `rtcontrol --tag "processed" completed=-12h`

```
Traceback (most recent call last):
  File "/home/youser/.local/bin/rtcontrol", line 8, in <module>
    sys.exit(run())
  File "/home/youser/.local/lib/python3.9/site-packages/pyrosimple/scripts/rtcontrol.py", line 908, in run
    RtorrentControl().run()
  File "/home/youser/.local/lib/python3.9/site-packages/pyrosimple/scripts/base.py", line 180, in run
    self.mainloop()
  File "/home/youser/.local/lib/python3.9/site-packages/pyrosimple/scripts/rtcontrol.py", line 806, in mainloop
    getattr(item, action["method"])(*args)
  File "/home/youser/.local/lib/python3.9/site-packages/pyrosimple/torrent/rtorrent.py", line 309, in tag
    tagset = previous.copy()
AttributeError: 'str' object has no attribute 'copy'
```

**Comment by kannibalox** [comment]
Thanks for the report, I'll have a new release out in a bit.

**Comment by BristleBeard** [comment]
Thank you! This fixed some issues I was also seeing with being able to return results using filters.

`rtcontrol '*HDTV*'` was not working but now does.
