### ISSUE TITLE
chtor error KeyError: <class 'pyrosimple.util.metafile.Metafile'>

### ISSUE THREAD

**Issue by stevezau** [kannibalox/pyrosimple#32]
Hi, I am trying to use chtor. This worked when using pyroscope. Not sure what I'm doing wrong? 

```
data@data:~/src/dotfiles$ chtor -RC -o /tmp /tor/data1/session/some.torrent
Traceback (most recent call last):
  File "/home/data/bin/chtor", line 8, in <module>
    sys.exit(run())
             ^^^^^
  File "/home/data/.venv/lib/python3.11/site-packages/pyrosimple/scripts/chtor.py", line 458, in run
    MetafileChanger().run()
  File "/home/data/.venv/lib/python3.11/site-packages/pyrosimple/scripts/base.py", line 173, in run
    self.mainloop()
  File "/home/data/.venv/lib/python3.11/site-packages/pyrosimple/scripts/chtor.py", line 405, in mainloop
    fh.write(bencode.bencode(torrent))
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/data/.venv/lib/python3.11/site-packages/bencodepy/__init__.py", line 85, in encode
    return self.encoder.encode(value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/data/.venv/lib/python3.11/site-packages/bencodepy/encoder.py", line 85, in encode
    self.encode_func[type(value)](value, r)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: <class 'pyrosimple.util.metafile.Metafile'>```

**Comment by stevezau** [comment]
I think it only happens when using -o
