### ISSUE TITLE
rtcontrol -V error

### ISSUE THREAD

**Issue by laplacesdaemon** [kannibalox/pyrosimple#40]
Calling rtcontrol with the  - V option fails with an error:

Traceback (most recent call last):
  File "/home/rtorrent/.local/bin/rtcontrol", line 8, in <module>
    sys.exit(run())
             ^^^^^
  File "/home/rtorrent/.local/pipx/venvs/pyrosimple/lib/python3.11/site-packages/pyrosimple/scripts/rtcontrol.py", line 1006, in run
    RtorrentControl().run()
  File "/home/rtorrent/.local/pipx/venvs/pyrosimple/lib/python3.11/site-packages/pyrosimple/scripts/base.py", line 177, in run
    self.mainloop()
  File "/home/rtorrent/.local/pipx/venvs/pyrosimple/lib/python3.11/site-packages/pyrosimple/scripts/rtcontrol.py", line 914, in mainloop
    self.show_in_view(view, matches)
  File "/home/rtorrent/.local/pipx/venvs/pyrosimple/lib/python3.11/site-packages/pyrosimple/scripts/rtcontrol.py", line 680, in show_in_view
    targetname = self.engine.show(

AttributeError: 'NoneType' object has no attribute 'show'

Version 2.7.1 works. The two versions above don't work for me.

**Comment by kannibalox** [comment]
Whoops, should be fixed now!
