### ISSUE TITLE
Unable to delete torrent

### ISSUE THREAD

**Issue by govardha** [kannibalox/pyrosimple#52]
Hello,

I was attempting a simple deletion of a torrent and I got this, am I doing something wrong?

```
someuser@node:~/bin$ rtcontrol hash=<hash> // --purge
2023-09-10 10:06:49 purge        <somefile>
purge? [Y)es, n)o, a)ll yes, q)uit]: Y
Traceback (most recent call last):
  File "/home/someuser/.local/bin/rtcontrol", line 8, in <module>
    sys.exit(run())
  File "/home/someuser/.local/lib/python3.10/site-packages/pyrosimple/scripts/rtcontrol.py", line 1047, in run
    RtorrentControl().run()
  File "/home/someuser/.local/lib/python3.10/site-packages/pyrosimple/scripts/base.py", line 181, in run
    self.mainloop()
  File "/home/someuser/.local/lib/python3.10/site-packages/pyrosimple/scripts/rtcontrol.py", line 944, in mainloop
    getattr(item, action["method"])(*args)
  File "/home/someuser/.local/lib/python3.10/site-packages/pyrosimple/torrent/rtorrent.py", line 529, in purge
    self.cull(file_filter=partial_file, attrs=["completed_chunks", "size_chunks"])
  File "/home/someuser/.local/lib/python3.10/site-packages/pyrosimple/torrent/rtorrent.py", line 568, in cull
    self._engine.logger.debug("Cleaning up directory '%s'", fullpath)
UnboundLocalError: local variable 'fullpath' referenced before assignment
```

**Comment by kannibalox** [comment]
This should be fixed in the latest code. I'm still double checking some other things for the next release, but should have it out sometime this afternoon.
